### ISSUE TITLE
TODO List (DB, bef. 10:00 16/03/2015)

### ISSUE THREAD

**Issue by dkanafeev** [RyabovaKseniya/course-work.Calendar.#3]
- [ ] Create SQL query
- [ ] Test your SQL query
- [ ] Add SQL query in code
- [ ] Write query result in UI elements
- [ ] Read query info from UI elements
- [ ] Test SQL query again (in UI)
